name: CI/CD Workflow

on:
  push:
    branches:
      - develop
      - master

jobs:
  linter-and-tests:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run npm install
        run: cd services/events-management && npm install

      - name: Run npm lint
        run: cd services/events-management && npm run lint

  # Job for the master branch: Docker build and push
  docker-build-and-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set this secret in GitHub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Set this secret in GitHub

      - name: Build and tag Docker image
        run: |
          VERSION=$(jq -r .version < package.json)
          docker build -t your-docker-username/your-service-name:v$VERSION .

      - name: Push Docker image
        run: |
          VERSION=$(jq -r .version < package.json)
          docker push your-docker-username/your-service-name:v$VERSION
