name: CI/CD Workflow

# Se ejecuta en push a los branches especificados
on:
  push:
    branches:
      - develop
      - master

jobs:
  # Trabajo para el branch develop
  linter-and-tests:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Cambia a la versión que necesites

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test

  # Trabajo para el branch master
  docker-build-and-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Configura este secret en GitHub
          password: ${{ secrets.DOCKER_PASSWORD }}  # Configura este secret en GitHub

      - name: Build and tag Docker image
        run: |
          VERSION=$(cat package.json | jq -r .version)
          docker build -t <user/nombre_servicio>:v$VERSION .

      - name: Push Docker image
        run: |
          VERSION=$(cat package.json | jq -r .version)
          docker push <user/nombre_servicio>:v$VERSION
